name: CI Build
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Get version
        id: version
        run: |
          version=$(grep '^version=' module.prop | cut -d '=' -f 2)
          echo "Version: $version" 
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Archive
        run:  |
          sudo zip -r MIUICamera_sm6225_${{steps.version.outputs.version}}.zip *  
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{steps.version.outputs.version}}
          tag_name: ${{steps.version.outputs.version}}
          files: MIUICamera_sm6225_${{steps.version.outputs.version}}.zip
      - name: Cleanup
        run:  |
          rm MIUICamera_sm6225_${{steps.version.outputs.version}}.zip